#+TITLE: org-roam-to-apple-notes

Learnings from my struggles to get Emacs, Apple Script and Apple Notes to all just get along.

* What can this do?

This package contains functions that can import a single org-roam node, or your whole database, into a folder called =org-roam= in your Apple Notes.

It's pretty useful that you can bulk export the lot with ~M-x oran-export-org-roam-nodes-to-apple-notes~, and then later do them ad hoc as you work on them with ~M-x oran-export-this-node-to-apple-notes~. Obviously, you can choose to live the one-by-one life from the start.

In spite of many hours of experimentation on my end, the truly crappy Apple Notes support in AppleScript does not allow any images to be imported. You'll get all of your text, and even nicely syntax-highlighted source code, but no images. This package will continue embedding all images as base64 regardless, in the probably ill-advised hope that Apple will one day improve their AppleScript support for Notes.

* Learnings

** No way of importing HTML into Notes with images

All of the following failed on macOS Sonoma 14.2, resulting in grey blocks in the imported notes. In all cases, the HTML is rendered well by the browser.

- Via Notes "Import to Notes" menu function:
  - HTML with absolute image src URLs to images outside of HTML dir
  - HTML with base64 embedded images
- Via AppleScript ~make new note ...~:
  - HTML with absolute image src URLs to images outside of HTML dir
  - HTML with base64 embedded images 

I also created a note purely in Notes, embedded an image, then exported the note body using AppleScript, confirmed that the exported body contained the base64 image, then created a new note with AppleScript using that exact same body. This too resulted in the dreaded grey, unusable block.

You can use [[./applescript/get-note-contents.applescript][get-note-contents.applescrip]] and ... to reproduce on your system.

** AppleScript silently truncates note titles to 70 characters

If a title is longer than 70 characters, it is displayed in full, but any AppleScript ~note named ...~ queries have to be done with the truncated version, with the ellipsis (~…~) appended.

Also, if you query such a note using AppleScript, it will only give you the truncated version.

** iCloud syncing of notes is unreliable with 1000+ imported notes

After importing my 1700+ notes database, iCloud managed to sync only the first 50 or so during the first day or two with spotty vacation wifi access.

I tried deleting the folder on the MacBook and iPhone and starting over. After this, iCloud was being very slow about syncing even a single manually created note from MacBook to iPhone, but after 15 minutes or so it seemed to start working. From here on I used the ~max-days~ argument to import only a smaller subsets of the full database.

This learning is still developing...

** Edit AppleScript with VSCode and the idleberg.applescript extension 

- much nicer environment than the built-in script editor
- github copilot
- run straight from vscode


